version: '3'

services:
  flaskapi:
    build: .
    container_name: flaskapi
    ports:
      - "5000:5000"
    volumes:
      -  ./:/code/
    command: "python main.py"
  
  database:
    container_name: postgres_database
    image: postgres:16.1-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
       - "5435:5432"